### ISSUE TITLE
Integration of gamma detection function

### ISSUE THREAD

**Issue by erex** [DistanceDevelopment/mrds#37]
Discussion on Distance [list](https://groups.google.com/g/distance-sampling/c/_g6PpL-74VQ) regarding use of gamma detection function, particularly with left truncation.  I've done a bit of snooping into the mrds code, finding the function `gstdint.R` doing the integration.

How does `gstdint.R` know the value of `distpdf` in the final `else` (which must be the way in which the integral is evaluated for the gamma) in [line 145](https://github.com/DistanceDevelopment/mrds/blob/8b9e96d1bd66aee74c3147a4c7546b548b663f8d/R/gstdint.R#L145)?

Might this be related to the issues raised by Steve on the Distance list?

**Comment by dill** [comment]
To answer your question: `distpdf` is a function, so the call on line 145 will use the detection function specification encoded in `ddfobj` to setup the detection function options correctly then integrate. Not sure if you were asking a deeper question there, please correct me if so.

I setup a simple example of this behaviour, based on Mitch's example:

```r
library(mrds)

set.seed(123)
par(mfrow=c(2,2))

# generate "distances"
gd <- rgamma(1000, 5, 1)


# format for mrds
egdata <- data.frame(distance = gd,
                     object   = 1:length(gd),
                     detected = 1,
                     observer = 1)

# fit model to "good" data
r <- ddf(dsmodel=~mcds(key="gamma", formula=~1), data=egdata, method="ds",
         meta.data=list(width=15))

# this looks fine
plot(r, which=1)
plot(r)


# what about if things are shifted
egdata2 <- egdata
egdata2$distance <- egdata2$distance + 5

# fit using left truncation
r2 <- ddf(dsmodel=~mcds(key="gamma", formula=~1), data=egdata2, method="ds",
         meta.data=list(left=5, width=20))

plot(r2, which=1)
plot(r2)
```

Which yields (top row "regular" distances, bottom shifted as I think is the case for Mitch's data):

![Screenshot 2021-11-17 at 15 31 30](https://user-images.githubusercontent.com/1953/142230660-0190eb14-2ead-4f63-a3b0-9ae879e53db6.png)

I have no intuition for gamma detection functions, but I assume that the detection functions should look the same if everything is working?

Looking at `summary` output:

```
> summary(r)

Summary for ds object
Number of observations :  1000 
Distance range         :  0  -  15 
AIC                    :  4253.486 

Detection function:
  key function 

Detection function parameters 
Scale coefficient(s): 
            estimate         se
(Intercept) 1.608815 0.02234909

Shape coefficient(s):  
            estimate        se
(Intercept) 1.383072 0.0556723

                        Estimate           SE         CV
Average p              0.3329089 7.380281e-03 0.02216907
N in covered region 3003.8248335 1.022430e+02 0.03403761
> summary(r2)

Summary for ds object
Number of observations :  1000 
Distance range         :  5  -  20 
AIC                    :  4301.843 

Detection function:
  key function 

Detection function parameters 
Scale coefficient(s): 
            estimate         se
(Intercept) 1.660321 0.02117715

Shape coefficient(s):  
            estimate         se
(Intercept) 3.004257 0.04960013

                        Estimate           SE         CV
Average p              0.3495885  0.007173389 0.02051952
N in covered region 2860.5062889 93.633525371 0.03273320
```

My guess is that parameter estimates will be different due to how the gamma works, but the probabilities of detection should be the same. So there might be some issue with the integration as you say.

Doing that integration manually, we get the results from the `summary`:

```r
ddfobj <- r$ds$aux$ddfobj
ddfobj$scale$dm <- ddfobj$scale$dm[1, ,drop=FALSE]
ddfobj$shape$dm <- ddfobj$shape$dm[1, ,drop=FALSE]
integrate(detfct, lower=0, upper=15, ddfobj=ddfobj)$value/15
```

```
[1] 0.3329089
```

```r
ddfobj2 <- r2$ds$aux$ddfobj
ddfobj2$scale$dm <- ddfobj2$scale$dm[1, ,drop=FALSE]
ddfobj2$shape$dm <- ddfobj2$shape$dm[1, ,drop=FALSE]
integrate(detfct, lower=5, upper=20, ddfobj=ddfobj2)$value/15
```

```
[1] 0.3495885
```

Stopping here for the day but will resume later.

**Comment by erex** [comment]
This is the only query to the list that involves a) fitting a gamma detection function and b) performing left-truncation.  Don't have any idea what is correct.

**Comment by dill** [comment]
Perhaps a more realistic example:

```r
library(mrds)

set.seed(123)
par(mfrow=c(3,1))

# generate "distances"
gd <- rgamma(1000, 2, 1)

# right truncation
width <- 5.5

# format for mrds
egdata <- data.frame(distance = gd,
                     object   = 1:length(gd),
                     detected = 1,
                     observer = 1)

# fit model to "good" data
r <- ddf(dsmodel=~mcds(key="gamma", formula=~1), data=egdata, method="ds",
         meta.data=list(width=width))

# this looks fine
plot(r, showpoints=FALSE)
title("good data")


# what about if we mess with the data
# drop some % of the data < some distance
missdist <- .5
dropind <- which(egdata$distance < missdist)
dropind2 <- which(egdata$distance >= missdist)
dropind <- sample(dropind, trunc(length(dropind)*.5))

egdata2 <- egdata[c(dropind, dropind2), ]


# fit ignoring left truncation
r2 <- ddf(dsmodel=~mcds(key="gamma", formula=~1), data=egdata2, method="ds",
         meta.data=list(left=0, width=width))

plot(r2, showpoints=FALSE)
title("data removed, no truncation")


# left truncation
r3 <- ddf(dsmodel=~mcds(key="gamma", formula=~1), data=egdata2, method="ds",
          meta.data=list(left=missdist, width=width))

plot(r3, showpoints=FALSE)
title(paste0("data removed, truncation at ", missdist))
```

Here I drop 50% of data very close to 0 (<.5).  Yielding the following plots:

![Screenshot 2021-11-18 at 16 54 38](https://user-images.githubusercontent.com/1953/142460650-feeed0bc-9b78-4909-839b-02d0bbb90c27.png)

Giving the following detectability estimates:

```
> summary(r)$average.p
[1] 0.4487827
> summary(r2)$average.p
[1] 0.4391756
> summary(r3)$average.p
[1] 0.4520211
```

My guess is that the model is somewhat sensitive to the placement of 0 distance (since this gives the point at which detections stop).

**Comment by erex** [comment]
The scenario you show above all seems sensible.  What emerges from the contrast between this most recent (sensible) scenario and that of Mitch that started this thread?  Any lessons we can pass along to users when fitting a gamma; avoid left-truncation or something more subtle?

**Comment by dill** [comment]
From the limited information here I think it's difficult to find general things to say, but I think it's probably fair to say that failing to truncate when you need to will lead to a lower p, so overestimate abundance. If the reverse pattern is generally true when truncating (gamma attenuated more towards zero, leading to a higher p, so underestimate of abundance) then it seems more conservative to go with the latter than the former.

I am looking into the "offset" chat that was in the e-mails to see if there are other approaches that I am not aware of, so please hold-off on going back to the list until I have investigated that.

**Comment by lenthomas** [comment]
I'll ask Steve to have a look at this thread and provide some additional comments, in case those are useful.

**Comment by dill** [comment]
It looks like this was a plotting issue (I checked various integration issues and it seems that the integration is being done right). This should now be resolved.
