### ISSUE TITLE
Monotonicity constraint consistency between `mrds` and Distance for Windows

### ISSUE THREAD

**Issue by dill** [DistanceDevelopment/mrds#62]
Per discussion [here](https://github.com/DistanceDevelopment/Distance/issues/133):

@lenthomas:

"Regarding the points at which to check for constraints, do you think I should change mcds.exe so that it also takes account of left truncation? It makes sense to me, as g(x) for 0 >= x >= [left trucation point] should be 0 when it comes to things like calculating average p so no point in checking for non-monotonicity there."

and

"[in mrds] there is a monotonicity check at 20 evenly spaced points between the left and right truncation points. This seems inconsistent with the constrained optimization that is done, where monotonicity is checked at 10 non-evenly spaced points between left and right truncation. Shouldn't these be consistent?"

**Comment by dill** [comment]
Check FORTRAN code, see if R does the same.

**Comment by lenthomas** [comment]
Decision at May 3rd Dist Dev meeting is to make the two consistent; we didn't finalize which to change, but it seems to make more sense a priori to have more constraint points rather than fewer.  If this is an mrds change it may warrant a minor version bump (e.g., 2.3 to 2.4) rather than just an increment at the "patch" level (e.g., 2.3.0 to 2.3.1).

**Comment by lenthomas** [comment]
In discussions around the IAA work with @fpetersma, we decided to make the `mrds` code consistent with what DistWin (MCDS.exe) currently does, which is checking at 10 points (not uniformly spaced and starting at 0 distance regardless of left truncation).  This has been implemented in `mrds` 2.0.0 so I will close this issue.
