### ISSUE TITLE
no date field in DESCRIPTION file of package ‘mrds’

### ISSUE THREAD

**Issue by lenthomas** [DistanceDevelopment/mrds#9]

**Comment by lenthomas** [comment]
Probably worth checking the other distance-related packages.  This issue was highlighted by a user who typed
citation("mrds")

**Comment by dill** [comment]
This is down to the lack of a date in the DESCRIPTION file in mrds. It's 
recommended that one doesn't put a date in there as it just goes out of 
date but this then leads to odd behaviour for citation(...).

This is a bug that has been fixed in R:

https://bugs.r-project.org/bugzilla3/show_bug.cgi?id=16550

but may not have made it into an R release yet (it's not on my machine, 
but I'm actually still running 3.2.3...)

**Comment by dill** [comment]
see also Hadley's reply [here](https://github.com/hadley/dplyr/issues/1442#issuecomment-145349226) on why not to include the date field in the DESCRIPTION.

**Comment by lenthomas** [comment]
Yes, you'd think the easy solution would be for citation to pull the date from the build date if it is missing in the date field...

**Comment by lenthomas** [comment]
... which is what they say they do in the fix
https://bugs.r-project.org/bugzilla3/show_bug.cgi?id=16550
which was made on 12th October last year (or 10th December, depending on how their date field works).
I'm running 
R version 3.2.4 Revised (2016-03-16 r70336)
and it doesn't appear to be in there.  Is it typical for a bug fix to take this long to make it into a build?

**Comment by jlaake** [comment]
I'll be there Monday and Wednesday. I'll come find you.
